### PR TITLE
WIP: Add refresh parameter to insert

### PR DESCRIPTION
**Pull request by aileo**
related to #13 

- Add return of the document id after insert (and related test)
- Add `refresh` parameter
  - can be `True`, `wait_for` or `False`, default and fallback to `False`
  - add to `es.index`

### CODE REVIEW

**Comment by aileo** [comment]
At this point, using `refresh 'wait_for'` and CTE allow to get the full document back with a join:

*using schema from tests*
```sql
WITH
inserted AS (
  INSERT INTO articles_es_wait_for (id, title, body)
  VALUES (2, 'test title', 'test body') RETURNING id
)
SELECT es.id, es.title, es.body FROM inserted
LEFT JOIN articles_es_wait_for as es ON es.id = inserted.id;

-- > 2 | test title | test body
```

Should the full return be implemented as this workaround if pretty light and save a call?

**Comment by matthewfranglen** [comment]
It doesn't really save a call? You still have to query the fdw to get the data.

This is where invoking the read method with the ids would be appropriate. I'm happy to take this on if you don't want to handle that.

**Comment by matthewfranglen** [comment]
I should be able to work on this a bit tonight.

**Review by matthewfranglen — APPROVED** [review]

**Comment by matthewfranglen** [comment]
I've ended up smashing a few unrelated changes in here too.

**Pull request merged**
